# Generated by Django 4.0.4 on 2022-06-05 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event_Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('event_one', models.ImageField(blank=True, upload_to='event_dashboard/')),
                ('slug', models.SlugField()),
            ],
        ),
    ]
