# Generated by Django 4.0.4 on 2022-06-06 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event_Dashboard',
        ),
    ]
