# Generated by Django 4.0.4 on 2022-06-06 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eventapp', '0002_delete_event_dashboard'),
    ]

    operations = [
        migrations.CreateModel(
            name='banner_event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_event_name', models.CharField(max_length=100)),
                ('banner_event_image', models.ImageField(blank=True, upload_to='banner_event_media')),
                ('slug', models.SlugField()),
            ],
        ),
    ]
